[package]
name = "link-async-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

publish = false

[lib]
doctest = false
test = true
doc = false

[features]
test = []

[dependencies]
futures = "0.3"

[dependencies.tokio]
version = "1"
features = ["macros", "rt-multi-thread", "time"]

[dependencies.link-async]
path = ".."
