[package]
name = "link-identities-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

publish = false

[lib]
doctest = false
test = true
doc = false

[features]
test = []

[dependencies]
anyhow = "1"
either = "1"
once_cell = "1"
proptest = "1"
serde = "1"
url = "2"
nonempty = "0.7"

[dependencies.git2]
version = ">= 0.13.24"
default-features = false
features = ["vendored-libgit2"]

[dependencies.librad]
path = "../../librad"

[dependencies.link-canonical]
path = "../../link-canonical"

[dependencies.link-crypto]
path = "../../link-crypto"

[dependencies.link-identities]
path = ".."

[dependencies.radicle-git-ext]
path = "../../git-ext"

[dependencies.radicle-std-ext]
path = "../../std-ext"

[dependencies.link-canonical-test]
path = "../../link-canonical/t"
features = ["test"]

[dependencies.link-crypto-test]
path = "../../link-crypto/t"
features = ["test"]


[dev-dependencies]
assert_matches = "1.5"
lazy_static = "1"
multihash = "0.11"
pretty_assertions = "1.1"
rand = "0.8"
serde_json = "1"
sha-1 = "0.10"
sized-vec = "0.3"
typenum = "1.13"

[dev-dependencies.radicle-std-ext]
path = "../../std-ext"

[dev-dependencies.test-helpers]
path = "../../test/test-helpers"

[dev-dependencies.it-helpers]
path = "../../test/it-helpers"
