[package]
name = "librad"
version = "0.1.0"
authors = ["The Radicle Team <dev@radicle.xyz>"]
edition = "2018"
license = "GPL-3.0-or-later"

[features]
default = []
disco-mdns = ["mdns", "madness"]

[dependencies]
async-trait = "0.1"
bit-vec = "0.6"
bs58 = "0.3"
bytes = "0.5"
dashmap = "4.0"
directories = "3.0"
dyn-clone = "1.0"
futures-timer = "3.0"
globset = "0.4"
governor = "0.3"
lazy_static = "1"
libc = "0.2"
mdns = { version = "1", optional = true }
multibase = "0.9"
multihash = "0.11"
nom = "5"
nonempty = "0.6"
nonzero_ext = "0.2"
num_cpus = "1"
parking_lot = "0.11"
percent-encoding = "2"
picky-asn1 = "0.3"
picky-asn1-der = "0.2"
picky-asn1-x509 = "0.4"
pnet_datalink = "0.27"
radicle-keystore = "0"
rand = "0.7"
rand_pcg = "0.2"
regex = "1.3"
rustc-hash = "1.1"
serde_bytes = "0.11"
serde_json = "1.0"
siphasher = "0.3"
tempfile = "3.1"
thiserror = "1.0"
time = "0.2"
tracing = "0.1"
tracing-futures = "0.2"
unicode-normalization = "0.1"
webpki = "0.21"

[dependencies.bloom_filter_simple]
git = "https://github.com/radicle-dev/bloom_filter_simple"
rev = "d4e5200304227d576ff44b5d5faf50017b297bfe"

[dependencies.deadpool]
version = "0.5"
default-features = false
features = ["managed"]

[dependencies.ed25519-zebra]
git = "https://github.com/ZcashFoundation/ed25519-zebra"
rev = "0e7a96a267a756e642e102a28a44dd79b9c7df69"

[dependencies.either]
version = ">= 1.3, 1"
features = ["serde"]

[dependencies.futures]
version = "0.3"
features = ["thread-pool"]

[dependencies.futures_codec]
version = "0.4"
features = []

[dependencies.git2]
version = ">= 0.13.12, 0.13"
default-features = false
features = []

[dependencies.libgit2-sys]
version = "0.12"
default-features = false
features = []

[dependencies.madness]
git = "https://github.com/meilisearch/madness"
rev = "cb12159a06f3698d0ba4ea078e95f8a915a9a9d3"
optional = true

[dependencies.minicbor]
version = ">= 0.6, 0"
features = ["std", "derive"]

[dependencies.quinn]
git = "https://github.com/quinn-rs/quinn"
rev = "47232c83d1615e96b4a8480ec25fbf7fcf6771f5"
default-features = false
features = ["tls-rustls"]

[dependencies.radicle-git-ext]
path = "../git-ext"

[dependencies.radicle-macros]
path = "../macros"

[dependencies.radicle-std-ext]
path = "../std-ext"

# Note: this MUST always match the exact patch version `quinn` uses
[dependencies.rustls]
git = "https://github.com/ctz/rustls"
rev = "fee894f7e030"
features = ["logging", "dangerous_configuration"]

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.tokio]
version = "0.2"
features = ["full"]

[dependencies.tokio-util]
version = "0.3"
features = ["compat"]

[dependencies.url]
version = "2.1"
features = ["serde"]

# TODO: a more popular alternative is the `twox-hash` crate, but it hasn't
# merged the stable xxh3 yet. There are also bindings to the C reference
# implementation (`xxhash-c`, by the same authors). `xxhash-rust` tests against
# this.
[dependencies.xxhash-rust]
version = "0.8"
features = ["xxh3"]

[dependencies.zeroize]
version = "1.1"
features = ["zeroize_derive"]

[dev-dependencies]
anyhow = "1"
argh = "0"
assert_matches = "1"
env_logger = "0"
fnv = "1"
futures-await-test = "0"
futures_ringbuf = "0"
log = "0.4"
nonempty = "0.6"
pretty_assertions = "0"
proptest = "0"
tracing-subscriber = ">= 0.2"

[dev-dependencies.librad-test]
path = "../librad-test"
