[package]
name = "lnk-identities"
version = "0.1.0"
authors = [ "Fintan Halpenny <fintan.halpenny@gmail.com>" ]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
doctest = false
test = false

[dependencies]
anyhow = "1.0"
clap = "2.33"
either = "1.0"
lazy_static = "1"
nonempty = "0.6"
serde_json = "1.0"
structopt = "0.3"
thiserror = "1.0"
tracing = "0.1"

[dependencies.lnk-clib]
path = "../lnk-clib"

[dependencies.git2]
version = ">= 0.13.23"
default-features = false
features = ["vendored-libgit2"]

[dependencies.libgit2-sys]
version = ">= 0.12.24"
default-features = false
features = ["vendored"]

[dependencies.librad]
path = "../../librad"

[dependencies.radicle-git-ext]
path = "../../git-ext"

[dependencies.radicle-std-ext]
path = "../../std-ext"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.similar]
version = "2.1"
features = [ "text" ]

[dependencies.thrussh-agent]
git = "https://github.com/FintanH/thrussh"
branch = "generic-agent"
default-features = false

[dependencies.url]
version = "2.1"
features = ["serde"]
