[package]
name = "git-helpers-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

publish = false

[lib]
doctest = false
test = true
doc = false

[[bin]]
name = "git-remote-rad"
path = "../src/bin/remote/main.rs"
doc = false

[features]
test = []

[dependencies]
anyhow = "1"

[dependencies.radicle-git-helpers]
path = ".."

[dev-dependencies]
tempfile = "3.3"

[dev-dependencies.git2]
version = "0.13.24"
default-features = false
features = ["vendored-libgit2"]

[dev-dependencies.test-helpers]
path = "../../test/test-helpers"

[dev-dependencies.it-helpers]
path = "../../test/it-helpers"

[dev-dependencies.librad]
path = "../../librad"
