[package]
name = "lnk-clib-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

publish = false

[lib]
doctest = false
test = true
doc = false

[[example]]
name = "echo"

[features]
test = []

[dev-dependencies]
anyhow = "1"
tempfile = "3.3"
proptest = "1"
pretty_assertions = "1.1"
socket2 = "0.4.4"
nix = "0"

[dev-dependencies.it-helpers]
path = "../../../test/it-helpers"

[dev-dependencies.test-helpers]
path = "../../../test/test-helpers"

[dev-dependencies.librad]
path = "../../../librad"

[dev-dependencies.lnk-clib]
path = ".."

[dev-dependencies.link-crypto-test]
path = "../../../link-crypto/t"
features = ["test"]

[dev-dependencies.tokio]
version = "1.13"
features = ["rt-multi-thread"]
