[package]
name = "node-lib-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

publish = false

[lib]
doctest = false
test = true
doc = false

[[example]]
name = "socket_activation_wrapper"

[[example]]
name = "socket_activation"

[features]
test = []

[dependencies]
proptest = "1"

[dependencies.git2]
version = "0.13.24"
default-features = false
features = ["vendored-libgit2"]

[dev-dependencies]
anyhow = "1"
assert_cmd = "2"
assert_matches = "1.5"
futures = "0.3"
nix = "0"
pretty_assertions = "1.1"
structopt = "0.3"
tempfile = "3.3"

[dev-dependencies.tokio]
version = "1.13"
features = ["rt-multi-thread"]

[dependencies.node-lib]
path = ".."

[dev-dependencies.librad]
path = "../../librad"

[dependencies.link-identities-test]
path = "../../link-identities/t"
features = ["test"]
