[package]
name = "lnk-clib"
version = "0.1.0"
authors = [ "Fintan Halpenny <fintan.halpenny@gmail.com>" ]
edition = "2018"
license = "GPL-3.0-or-later"

[lib]
doctest = false
test = false

[features]
unsafe = []

[dependencies]
futures-lite = "1.12.0"
itertools = "0.10.0"
nix = "0.23.1"
once_cell = "1.10"
serde = "1.0"
serde_json = "1.0"
socket2 = "0.4.4"
thiserror = "1.0"
tracing = "0.1"

[dependencies.librad]
path = "../../librad"

[dependencies.lnk-thrussh-agent]
version = "0.1.0"
features = [ "tokio-agent" ]

[dependencies.minicbor]
version = "0.13"
features = ["std"]

[dependencies.tokio]
version = "1.13"
default-features = false
features = [ "fs", "io-std", "macros", "process", "rt-multi-thread", "signal" ]
