[package]
name = "lnk-exe-test"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-or-later"

publish = false

[lib]
doctest = false
test = true
doc = false

[features]
test = []

[dev-dependencies]
rusty-fork = "0.3"
lnk-exe = { path = ".." }
